[package]
name = "nes"
version = "0.1.0"
authors = ["Luke Triantafyllidis <ltriant@cpan.org>"]
edition = "2018"

[dependencies]
log = "0.4.4"
env_logger = "0.5.13"
sdl2 = "0.32.2"
lazy_static = "1.3.0"
md5 = "0.6.1"
